# Generated by Django 6.1 on 2026-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_product_daily_sales_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
