# Generated by Django 6.1 on 2026-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(
                blank=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(
                blank=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True
            ),
        ),
    ]