# Generated by Django 6.1 on 2026-09-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='daily_sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
